controllers:
    resource: ../src/Controller/
    type: attribute
api_login_check:
    path: /api/login_check

# Artisan
liste_devis_par_artisan:
    path: /listeDevisParArtisan
    methods: [GET]
    controller: App\Controller\API\DevisClientApiController::listeDevisParArtisan
visualiser_devis_artisan:
    path: /visualiserDevisArtisan
    methods: [GET]
    controller: App\Controller\API\DevisClientApiController::visualiserDevisArtisan
visualiser_devis_artisan_a_preparer:
    path: /visualiserDevisArtisanApreparer
    methods: [GET]
    controller: App\Controller\API\DevisClientApiController::visualiserDevisArtisanApreparer
preparer_devis:
    path: /preparerDevis/{id}/{montant}
    methods: [PATCH]
    controller: App\Controller\API\DevisClientApiController::preparerDevis

 # Utilisateur   
connexion_utilisateur:
    path: /connexion_utilisateur
    methods: [POST]
    controller: App\Controller\API\UtilisateurController::connexionUtilisateur
reception_devis:
    path: /receptionDevis/{email}
    methods: [GET]
    controller: App\Controller\API\UtilisateurController::receptionDevis
visualiser_devis_client:
    path: /visualiserDevisClient/{id}
    methods: [GET]
    controller: App\Controller\API\UtilisateurController::visualiserDevisClient
valider_devis_client:
    path: /validerDevis/{id}
    methods: [PATCH]
    controller: App\Controller\API\UtilisateurController::validerDevis
refuser_devis_client:
    path: /refuserDevis/{id}
    methods: [PATCH]
    controller: App\Controller\API\UtilisateurController::refuserDevis
supprimer_devis_client:
    path: /supprimerDevis/{id}
    methods: [DELETE]
    controller: App\Controller\API\UtilisateurController::supprimerDevis
reception_devis_par_id:
    path: /receptionDevisParId/{id}
    methods: [GET]
    controller: App\Controller\API\UtilisateurController::receptionDevisParId
demande_intervention:
    path: /demandeIntervention
    methods: [POST]
    controller: App\Controller\API\UtilisateurController::demandeIntervention
set_demande_devis_etat:
    path: /setDemandeDevisEtat/{id}
    methods: [PATCH]
    controller: App\Controller\API\UtilisateurController::setDemandeDevisEtat